version: '3.1'

services:
  php:
    container_name: my_php_container__
    build:
      context: ./php #.
      dockerfile: ./Dockerfile # ./php/Dockerfile #
    volumes:
      - ./php/index.php:/usr/src/myapp/index.php
      - ./php/composer.json:/usr/src/myapp/composer.json
    ports:
      - "8080:8080"